#!/usr/bin/env python3
"""Generate characters.json for Chinese Writing Practice App."""
import json

# Format: (simplified, traditional, pinyin, meaning, word, wordTrad, wordPinyin, wordMeaning)
# ttsText is auto-generated as "X，YZ的X"

GRADE1 = [
("一","一","yī","one","一个","一個","yī gè","one (of)"),
("二","二","èr","two","第二","第二","dì èr","second"),
("三","三","sān","three","三个","三個","sān gè","three (of)"),
("上","上","shàng","up; above","上学","上學","shàng xué","go to school"),
("口","口","kǒu","mouth","人口","人口","rén kǒu","population"),
("目","目","mù","eye","目光","目光","mù guāng","gaze"),
("耳","耳","ěr","ear","耳朵","耳朵","ěr duo","ear"),
("手","手","shǒu","hand","手机","手機","shǒu jī","phone"),
("日","日","rì","day; sun","日子","日子","rì zi","day"),
("田","田","tián","field","田地","田地","tián dì","farmland"),
("禾","禾","hé","grain","禾苗","禾苗","hé miáo","seedling"),
("火","火","huǒ","fire","火车","火車","huǒ chē","train"),
("虫","蟲","chóng","insect","虫子","蟲子","chóng zi","bug"),
("云","雲","yún","cloud","白云","白雲","bái yún","white cloud"),
("山","山","shān","mountain","山上","山上","shān shàng","on the mountain"),
("八","八","bā","eight","八个","八個","bā gè","eight (of)"),
("十","十","shí","ten","十个","十個","shí gè","ten (of)"),
("人","人","rén","person","大人","大人","dà rén","adult"),
("大","大","dà","big","大家","大家","dà jiā","everyone"),
("天","天","tiān","sky; day","天空","天空","tiān kōng","sky"),
("四","四","sì","four","四个","四個","sì gè","four (of)"),
("五","五","wǔ","five","五个","五個","wǔ gè","five (of)"),
("六","六","liù","six","六个","六個","liù gè","six (of)"),
("七","七","qī","seven","七个","七個","qī gè","seven (of)"),
("九","九","jiǔ","nine","九个","九個","jiǔ gè","nine (of)"),
("个","個","gè","measure word","一个","一個","yī gè","one (of)"),
("月","月","yuè","moon; month","月亮","月亮","yuè liang","moon"),
("儿","兒","ér","child; son","儿子","兒子","ér zi","son"),
("头","頭","tóu","head","头发","頭髮","tóu fa","hair"),
("里","裡","lǐ","inside","里面","裡面","lǐ miàn","inside"),
("可","可","kě","may; can","可以","可以","kě yǐ","can"),
("东","東","dōng","east","东方","東方","dōng fāng","east"),
("西","西","xī","west","东西","東西","dōng xi","thing"),
("是","是","shì","is; yes","不是","不是","bú shì","is not"),
("不","不","bù","not","不好","不好","bù hǎo","not good"),
("对","對","duì","correct","对不起","對不起","duì bu qǐ","sorry"),
("开","開","kāi","open","开心","開心","kāi xīn","happy"),
("关","關","guān","close","关门","關門","guān mén","close door"),
("正","正","zhèng","correct","正在","正在","zhèng zài","currently"),
("反","反","fǎn","opposite","反面","反面","fǎn miàn","reverse side"),
("王","王","wáng","king","国王","國王","guó wáng","king"),
("石","石","shí","stone","石头","石頭","shí tou","stone"),
("小","小","xiǎo","small","小心","小心","xiǎo xīn","careful"),
("少","少","shǎo","few","多少","多少","duō shǎo","how many"),
("刀","刀","dāo","knife","小刀","小刀","xiǎo dāo","small knife"),
("力","力","lì","power","力气","力氣","lì qi","strength"),
("尺","尺","chǐ","ruler","尺子","尺子","chǐ zi","ruler"),
("本","本","běn","root; book","本子","本子","běn zi","notebook"),
("文","文","wén","writing","语文","語文","yǔ wén","Chinese class"),
("左","左","zuǒ","left","左边","左邊","zuǒ biān","left side"),
("右","右","yòu","right","右边","右邊","yòu biān","right side"),
("水","水","shuǐ","water","水果","水果","shuǐ guǒ","fruit"),
("书","書","shū","book","读书","讀書","dú shū","study"),
("来","來","lái","come","过来","過來","guò lái","come over"),
("回","回","huí","return","回家","回家","huí jiā","go home"),
("片","片","piàn","piece","一片","一片","yī piàn","a piece"),
("皮","皮","pí","skin","皮球","皮球","pí qiú","ball"),
("生","生","shēng","life; birth","学生","學生","xué shēng","student"),
("果","果","guǒ","fruit","水果","水果","shuǐ guǒ","fruit"),
("几","幾","jǐ","how many","几个","幾個","jǐ gè","how many"),
("用","用","yòng","use","用心","用心","yòng xīn","attentive"),
("鱼","魚","yú","fish","小鱼","小魚","xiǎo yú","small fish"),
("今","今","jīn","today","今天","今天","jīn tiān","today"),
("长","長","cháng","long","长大","長大","zhǎng dà","grow up"),
("方","方","fāng","square","方向","方向","fāng xiàng","direction"),
("半","半","bàn","half","一半","一半","yī bàn","half"),
("巴","巴","bā","hope","尾巴","尾巴","wěi ba","tail"),
("把","把","bǎ","hold","把手","把手","bǎ shǒu","handle"),
("下","下","xià","down","下面","下面","xià miàn","below"),
("门","門","mén","door","开门","開門","kāi mén","open door"),
("们","們","men","plural","我们","我們","wǒ men","we"),
("你","你","nǐ","you","你好","你好","nǐ hǎo","hello"),
("我","我","wǒ","I; me","我们","我們","wǒ men","we"),
("他","他","tā","he","他们","他們","tā men","they"),
("她","她","tā","she","她们","她們","tā men","they (f)"),
("白","白","bái","white","白色","白色","bái sè","white"),
("的","的","de","(particle)","我的","我的","wǒ de","my"),
("了","了","le","(particle)","好了","好了","hǎo le","done"),
("又","又","yòu","again","又大又圆","又大又圓","yòu dà yòu yuán","big and round"),
("和","和","hé","and","和平","和平","hé píng","peace"),
("在","在","zài","at; in","在家","在家","zài jiā","at home"),
("有","有","yǒu","have","没有","沒有","méi yǒu","don't have"),
("子","子","zǐ","child","孩子","孩子","hái zi","child"),
("也","也","yě","also","也是","也是","yě shì","also is"),
("么","麼","me","(suffix)","什么","什麼","shén me","what"),
("多","多","duō","many","多少","多少","duō shǎo","how many"),
("出","出","chū","go out","出去","出去","chū qù","go out"),
("见","見","jiàn","see","看见","看見","kàn jiàn","see"),
("两","兩","liǎng","two (of)","两个","兩個","liǎng gè","two (of)"),
("就","就","jiù","then","就是","就是","jiù shì","precisely"),
("竹","竹","zhú","bamboo","竹子","竹子","zhú zi","bamboo"),
]

GRADE2 = [
("春","春","chūn","spring","春天","春天","chūn tiān","spring"),
("冬","冬","dōng","winter","冬天","冬天","dōng tiān","winter"),
("风","風","fēng","wind","大风","大風","dà fēng","strong wind"),
("花","花","huā","flower","花朵","花朵","huā duǒ","flower"),
("飞","飛","fēi","fly","飞机","飛機","fēi jī","airplane"),
("入","入","rù","enter","进入","進入","jìn rù","enter"),
("姓","姓","xìng","surname","姓名","姓名","xìng míng","full name"),
("什","什","shén","what","什么","什麼","shén me","what"),
("双","雙","shuāng","pair","一双","一雙","yī shuāng","a pair"),
("国","國","guó","country","中国","中國","zhōng guó","China"),
("方","方","fāng","direction","方法","方法","fāng fǎ","method"),
("青","青","qīng","green/blue","青草","青草","qīng cǎo","green grass"),
("清","清","qīng","clear","清水","清水","qīng shuǐ","clear water"),
("气","氣","qì","air","天气","天氣","tiān qì","weather"),
("晴","晴","qíng","sunny","晴天","晴天","qíng tiān","sunny day"),
("情","情","qíng","feeling","心情","心情","xīn qíng","mood"),
("请","請","qǐng","please","请问","請問","qǐng wèn","excuse me"),
("字","字","zì","character","写字","寫字","xiě zì","write"),
("红","紅","hóng","red","红色","紅色","hóng sè","red"),
("时","時","shí","time","时间","時間","shí jiān","time"),
("动","動","dòng","move","运动","運動","yùn dòng","exercise"),
("万","萬","wàn","ten thousand","一万","一萬","yī wàn","10,000"),
("吃","吃","chī","eat","吃饭","吃飯","chī fàn","eat rice"),
("叫","叫","jiào","call","叫做","叫做","jiào zuò","called"),
("主","主","zhǔ","master","主人","主人","zhǔ rén","master"),
("江","江","jiāng","river","长江","長江","cháng jiāng","Yangtze"),
("住","住","zhù","live","住在","住在","zhù zài","live at"),
("没","沒","méi","not have","没有","沒有","méi yǒu","don't have"),
("以","以","yǐ","with; by","可以","可以","kě yǐ","can"),
("会","會","huì","can; meet","学会","學會","xué huì","learn"),
("走","走","zǒu","walk","走路","走路","zǒu lù","walk"),
("北","北","běi","north","北方","北方","běi fāng","north"),
("京","京","jīng","capital","北京","北京","běi jīng","Beijing"),
("广","廣","guǎng","wide","广大","廣大","guǎng dà","vast"),
("过","過","guò","pass","过去","過去","guò qù","past"),
("各","各","gè","each","各种","各種","gè zhǒng","various"),
("种","種","zhǒng","kind","种子","種子","zhǒng zi","seed"),
("样","樣","yàng","manner","一样","一樣","yī yàng","same"),
("伙","夥","huǒ","partner","伙伴","夥伴","huǒ bàn","partner"),
("伴","伴","bàn","companion","伙伴","夥伴","huǒ bàn","partner"),
("这","這","zhè","this","这个","這個","zhè gè","this one"),
("太","太","tài","too","太阳","太陽","tài yáng","sun"),
("阳","陽","yáng","sun","太阳","太陽","tài yáng","sun"),
("校","校","xiào","school","学校","學校","xué xiào","school"),
("金","金","jīn","gold","金色","金色","jīn sè","golden"),
("秋","秋","qiū","autumn","秋天","秋天","qiū tiān","autumn"),
("因","因","yīn","because","因为","因為","yīn wèi","because"),
("为","為","wèi","for","因为","因為","yīn wèi","because"),
("它","它","tā","it","它们","它們","tā men","they (things)"),
("安","安","ān","safe","安全","安全","ān quán","safe"),
("块","塊","kuài","piece","一块","一塊","yī kuài","one piece"),
("空","空","kōng","empty; sky","天空","天空","tiān kōng","sky"),
("海","海","hǎi","sea","大海","大海","dà hǎi","ocean"),
("连","連","lián","connect","连忙","連忙","lián máng","hurriedly"),
("军","軍","jūn","army","军人","軍人","jūn rén","soldier"),
("音","音","yīn","sound","声音","聲音","shēng yīn","sound"),
("远","遠","yuǎn","far","远方","遠方","yuǎn fāng","far away"),
("近","近","jìn","near","附近","附近","fù jìn","nearby"),
("还","還","hái","still","还是","還是","hái shì","still is"),
("进","進","jìn","enter","进去","進去","jìn qù","go in"),
("运","運","yùn","transport","运动","運動","yùn dòng","exercise"),
("池","池","chí","pond","水池","水池","shuǐ chí","pool"),
("欢","歡","huān","happy","欢乐","歡樂","huān lè","joy"),
("古","古","gǔ","ancient","古老","古老","gǔ lǎo","ancient"),
("凉","涼","liáng","cool","凉快","涼快","liáng kuai","cool"),
("细","細","xì","fine; thin","仔细","仔細","zǐ xì","careful"),
("夕","夕","xī","evening","除夕","除夕","chú xī","New Year's Eve"),
("外","外","wài","outside","外面","外面","wài miàn","outside"),
("计","計","jì","plan","计划","計劃","jì huà","plan"),
("记","記","jì","remember","记住","記住","jì zhù","remember"),
("加","加","jiā","add","加上","加上","jiā shàng","add"),
("星","星","xīng","star","星星","星星","xīng xing","star"),
("行","行","xíng","go; ok","行走","行走","xíng zǒu","walk"),
("名","名","míng","name","名字","名字","míng zi","name"),
("洗","洗","xǐ","wash","洗手","洗手","xǐ shǒu","wash hands"),
("扫","掃","sǎo","sweep","打扫","打掃","dǎ sǎo","clean up"),
("真","真","zhēn","true","真的","真的","zhēn de","really"),
("认","認","rèn","recognize","认识","認識","rèn shi","know"),
("父","父","fù","father","父亲","父親","fù qīn","father"),
("母","母","mǔ","mother","母亲","母親","mǔ qīn","mother"),
("教","教","jiāo","teach","教室","教室","jiào shì","classroom"),
("收","收","shōu","receive","收到","收到","shōu dào","receive"),
("女","女","nǚ","female","女人","女人","nǚ rén","woman"),
("完","完","wán","finish","完成","完成","wán chéng","complete"),
("家","家","jiā","home","大家","大家","dà jiā","everyone"),
("写","寫","xiě","write","写字","寫字","xiě zì","write"),
("看","看","kàn","look","看见","看見","kàn jiàn","see"),
("着","著","zhe","(particle)","看着","看著","kàn zhe","looking at"),
("笑","笑","xiào","laugh","微笑","微笑","wēi xiào","smile"),
("兴","興","xīng","excitement","高兴","高興","gāo xìng","happy"),
("快","快","kuài","fast","快乐","快樂","kuài lè","happy"),
("乐","樂","lè","happy","快乐","快樂","kuài lè","happy"),
("玩","玩","wán","play","好玩","好玩","hǎo wán","fun"),
("往","往","wǎng","toward","往前","往前","wǎng qián","forward"),
("觉","覺","jué","feel","感觉","感覺","gǎn jué","feel"),
("烧","燒","shāo","burn","发烧","發燒","fā shāo","fever"),
("知","知","zhī","know","知道","知道","zhī dào","know"),
("识","識","shí","know","认识","認識","rèn shi","know"),
("放","放","fàng","put; release","放学","放學","fàng xué","after school"),
("那","那","nà","that","那个","那個","nà gè","that one"),
("都","都","dōu","all","都是","都是","dōu shì","all are"),
("到","到","dào","arrive","到达","到達","dào dá","arrive"),
("高","高","gāo","tall","高兴","高興","gāo xìng","happy"),
("当","當","dāng","when","当时","當時","dāng shí","at that time"),
("要","要","yào","want","需要","需要","xū yào","need"),
("成","成","chéng","become","成功","成功","chéng gōng","succeed"),
("间","間","jiān","between","时间","時間","shí jiān","time"),
("已","已","yǐ","already","已经","已經","yǐ jīng","already"),
("豆","豆","dòu","bean","豆子","豆子","dòu zi","bean"),
("句","句","jù","sentence","一句","一句","yī jù","a sentence"),
("直","直","zhí","straight","一直","一直","yī zhí","always"),
("呢","呢","ne","(particle)","你呢","你呢","nǐ ne","and you?"),
("吗","嗎","ma","(question)","好吗","好嗎","hǎo ma","ok?"),
("吧","吧","ba","(suggestion)","走吧","走吧","zǒu ba","let's go"),
("足","足","zú","foot","足球","足球","zú qiú","soccer"),
("声","聲","shēng","sound","声音","聲音","shēng yīn","sound"),
("身","身","shēn","body","身体","身體","shēn tǐ","body"),
("体","體","tǐ","body","身体","身體","shēn tǐ","body"),
("之","之","zhī","of","之后","之後","zhī hòu","after"),
("相","相","xiāng","mutual","相信","相信","xiāng xìn","believe"),
("习","習","xí","study","学习","學習","xué xí","study"),
("义","義","yì","justice","意义","意義","yì yì","meaning"),
("玉","玉","yù","jade","玉石","玉石","yù shí","jade stone"),
("鸣","鳴","míng","cry (bird)","鸟鸣","鳥鳴","niǎo míng","birdsong"),
("朋","朋","péng","friend","朋友","朋友","péng you","friend"),
("友","友","yǒu","friend","朋友","朋友","péng you","friend"),
("话","話","huà","speech","说话","說話","shuō huà","speak"),
("回","回","huí","return","回来","回來","huí lái","come back"),
("土","土","tǔ","earth","土地","土地","tǔ dì","land"),
("公","公","gōng","public","公园","公園","gōng yuán","park"),
("全","全","quán","all","全部","全部","quán bù","all"),
("先","先","xiān","first","先生","先生","xiān shēng","mister"),
("干","乾","gān","dry","干净","乾淨","gān jìng","clean"),
("赶","趕","gǎn","hurry","赶快","趕快","gǎn kuài","hurry up"),
("起","起","qǐ","rise","起来","起來","qǐ lái","get up"),
("明","明","míng","bright","明天","明天","míng tiān","tomorrow"),
("节","節","jié","festival","节日","節日","jié rì","holiday"),
("叶","葉","yè","leaf","树叶","樹葉","shù yè","tree leaf"),
("米","米","mǐ","rice","大米","大米","dà mǐ","rice"),
("分","分","fēn","divide","分钟","分鐘","fēn zhōng","minute"),
("色","色","sè","color","颜色","顏色","yán sè","color"),
("听","聽","tīng","listen","听见","聽見","tīng jiàn","hear"),
("哥","哥","gē","brother","哥哥","哥哥","gē ge","brother"),
("单","單","dān","single","简单","簡單","jiǎn dān","simple"),
("打","打","dǎ","hit","打球","打球","dǎ qiú","play ball"),
("拍","拍","pāi","clap","拍手","拍手","pāi shǒu","clap hands"),
("跑","跑","pǎo","run","跑步","跑步","pǎo bù","run"),
("爸","爸","bà","dad","爸爸","爸爸","bà ba","dad"),
("妈","媽","mā","mom","妈妈","媽媽","mā ma","mom"),
("爷","爺","yé","grandpa","爷爷","爺爺","yé ye","grandpa"),
("奶","奶","nǎi","grandma","奶奶","奶奶","nǎi nai","grandma"),
("午","午","wǔ","noon","中午","中午","zhōng wǔ","noon"),
("弟","弟","dì","younger brother","弟弟","弟弟","dì di","brother"),
("丰","豐","fēng","abundant","丰富","豐富","fēng fù","rich"),
("群","群","qún","group","人群","人群","rén qún","crowd"),
("旗","旗","qí","flag","国旗","國旗","guó qí","national flag"),
("号","號","hào","number","号码","號碼","hào mǎ","number"),
("队","隊","duì","team","队伍","隊伍","duì wu","team"),
("许","許","xǔ","allow","也许","也許","yě xǔ","perhaps"),
("让","讓","ràng","let","让开","讓開","ràng kāi","step aside"),
("说","說","shuō","say","说话","說話","shuō huà","speak"),
("地","地","dì","ground","地方","地方","dì fang","place"),
("河","河","hé","river","河水","河水","hé shuǐ","river water"),
("画","畫","huà","draw","画画","畫畫","huà huà","draw"),
("拉","拉","lā","pull","拉手","拉手","lā shǒu","hold hands"),
]

GRADE3 = [
("游","遊","yóu","swim; travel","旅游","旅遊","lǚ yóu","travel"),
("泳","泳","yǒng","swim","游泳","游泳","yóu yǒng","swim"),
("棋","棋","qí","chess","下棋","下棋","xià qí","play chess"),
("弹","彈","tán","play (instrument)","弹琴","彈琴","tán qín","play piano"),
("钢","鋼","gāng","steel","钢琴","鋼琴","gāng qín","piano"),
("琴","琴","qín","instrument","钢琴","鋼琴","gāng qín","piano"),
("养","養","yǎng","raise","养育","養育","yǎng yù","nurture"),
("航","航","háng","navigate","航空","航空","háng kōng","aviation"),
("模","模","mó","model","模型","模型","mó xíng","model"),
("建","建","jiàn","build","建设","建設","jiàn shè","build"),
("筑","築","zhù","construct","建筑","建築","jiàn zhù","architecture"),
("特","特","tè","special","特别","特別","tè bié","special"),
("产","產","chǎn","produce","产品","產品","chǎn pǐn","product"),
("旅","旅","lǚ","travel","旅游","旅遊","lǚ yóu","travel"),
("社","社","shè","society","社会","社會","shè huì","society"),
("照","照","zhào","shine; photo","照片","照片","zhào piàn","photo"),
("商","商","shāng","commerce","商店","商店","shāng diàn","store"),
("物","物","wù","thing","动物","動物","dòng wù","animal"),
("根","根","gēn","root","根本","根本","gēn běn","fundamental"),
("湖","湖","hú","lake","湖水","湖水","hú shuǐ","lake water"),
("界","界","jiè","boundary","世界","世界","shì jiè","world"),
("醒","醒","xǐng","wake up","清醒","清醒","qīng xǐng","sober"),
("列","列","liè","row","排列","排列","pái liè","arrange"),
("展","展","zhǎn","show","展览","展覽","zhǎn lǎn","exhibition"),
("品","品","pǐn","goods","产品","產品","chǎn pǐn","product"),
("圈","圈","quān","circle","一圈","一圈","yī quān","one circle"),
("彩","彩","cǎi","color","色彩","色彩","sè cǎi","color"),
("壮","壯","zhuàng","strong","壮大","壯大","zhuàng dà","strengthen"),
("章","章","zhāng","chapter","文章","文章","wén zhāng","article"),
("表","表","biǎo","surface","表面","表面","biǎo miàn","surface"),
("演","演","yǎn","perform","表演","表演","biǎo yǎn","perform"),
("够","夠","gòu","enough","足够","足夠","zú gòu","enough"),
("猜","猜","cāi","guess","猜想","猜想","cāi xiǎng","guess"),
("巨","巨","jù","huge","巨大","巨大","jù dà","huge"),
("位","位","wèi","position","座位","座位","zuò wèi","seat"),
("布","布","bù","cloth","布料","布料","bù liào","fabric"),
("祝","祝","zhù","wish","祝福","祝福","zhù fú","blessing"),
("贺","賀","hè","congratulate","祝贺","祝賀","zhù hè","congratulate"),
("希","希","xī","hope","希望","希望","xī wàng","hope"),
("精","精","jīng","essence","精彩","精彩","jīng cǎi","wonderful"),
("准","準","zhǔn","allow","准备","準備","zhǔn bèi","prepare"),
("备","備","bèi","prepare","准备","準備","zhǔn bèi","prepare"),
("提","提","tí","lift","提高","提高","tí gāo","improve"),
("确","確","què","sure","确实","確實","què shí","indeed"),
("信","信","xìn","believe","相信","相信","xiāng xìn","believe"),
("赞","讚","zàn","praise","赞美","讚美","zàn měi","praise"),
("错","錯","cuò","wrong","错误","錯誤","cuò wù","mistake"),
("断","斷","duàn","break","判断","判斷","pàn duàn","judge"),
("续","續","xù","continue","继续","繼續","jì xù","continue"),
("决","決","jué","decide","决定","決定","jué dìng","decide"),
("组","組","zǔ","group","小组","小組","xiǎo zǔ","group"),
("桥","橋","qiáo","bridge","大桥","大橋","dà qiáo","bridge"),
("险","險","xiǎn","danger","危险","危險","wēi xiǎn","danger"),
("洪","洪","hóng","flood","洪水","洪水","hóng shuǐ","flood"),
("减","減","jiǎn","reduce","减少","減少","jiǎn shǎo","reduce"),
("灾","災","zāi","disaster","灾难","災難","zāi nàn","disaster"),
("服","服","fú","clothes","衣服","衣服","yī fu","clothes"),
("街","街","jiē","street","街道","街道","jiē dào","street"),
("管","管","guǎn","manage","管理","管理","guǎn lǐ","manage"),
("具","具","jù","tool","工具","工具","gōng jù","tool"),
("屋","屋","wū","house","房屋","房屋","fáng wū","house"),
("紧","緊","jǐn","tight","紧张","緊張","jǐn zhāng","nervous"),
("标","標","biāo","mark","标准","標準","biāo zhǔn","standard"),
("宫","宮","gōng","palace","皇宫","皇宮","huáng gōng","palace"),
("团","團","tuán","group","团队","團隊","tuán duì","team"),
("翻","翻","fān","turn over","翻开","翻開","fān kāi","open (book)"),
("倒","倒","dǎo","fall over","倒下","倒下","dǎo xià","fall down"),
("猫","貓","māo","cat","小猫","小貓","xiǎo māo","kitten"),
("环","環","huán","ring","环境","環境","huán jìng","environment"),
("境","境","jìng","boundary","环境","環境","huán jìng","environment"),
("注","注","zhù","pour; note","注意","注意","zhù yì","attention"),
("黑","黑","hēi","black","黑色","黑色","hēi sè","black"),
]

GRADE4 = [
("潮","潮","cháo","tide","潮水","潮水","cháo shuǐ","tide"),
("称","稱","chēng","call","称呼","稱呼","chēng hu","address"),
("笼","籠","lóng","cage","鸟笼","鳥籠","niǎo lóng","birdcage"),
("雾","霧","wù","fog","大雾","大霧","dà wù","heavy fog"),
("灿","燦","càn","brilliant","灿烂","燦爛","càn làn","brilliant"),
("烂","爛","làn","rotten","灿烂","燦爛","càn làn","brilliant"),
("竿","竿","gān","pole","竹竿","竹竿","zhú gān","bamboo pole"),
("茫","茫","máng","vast","茫茫","茫茫","máng máng","vast"),
("桨","槳","jiǎng","oar","船桨","船槳","chuán jiǎng","oar"),
("规","規","guī","rule","规律","規律","guī lǜ","rule"),
("律","律","lǜ","law","法律","法律","fǎ lǜ","law"),
("支","支","zhī","branch","支持","支持","zhī chí","support"),
("触","觸","chù","touch","接触","接觸","jiē chù","contact"),
("痕","痕","hén","mark","痕迹","痕跡","hén jì","trace"),
("迹","跡","jì","trace","痕迹","痕跡","hén jì","trace"),
("均","均","jūn","equal","平均","平均","píng jūn","average"),
("叠","疊","dié","fold","重叠","重疊","chóng dié","overlap"),
("茎","莖","jīng","stem","花茎","花莖","huā jīng","flower stem"),
("占","佔","zhàn","occupy","占领","佔領","zhàn lǐng","occupy"),
("若","若","ruò","if","若是","若是","ruò shì","if"),
("罩","罩","zhào","cover","笼罩","籠罩","lǒng zhào","shroud"),
("屹","屹","yì","stand firm","屹立","屹立","yì lì","stand firm"),
("辉","輝","huī","splendor","光辉","光輝","guāng huī","glory"),
("庙","廟","miào","temple","寺庙","寺廟","sì miào","temple"),
("贸","貿","mào","trade","贸易","貿易","mào yì","trade"),
("超","超","chāo","surpass","超过","超過","chāo guò","exceed"),
("灌","灌","guàn","irrigate","灌溉","灌溉","guàn gài","irrigate"),
("核","核","hé","core","核心","核心","hé xīn","core"),
("荣","榮","róng","glory","光荣","光榮","guāng róng","glorious"),
("毁","毀","huǐ","destroy","毁坏","毀壞","huǐ huài","destroy"),
("慧","慧","huì","wise","智慧","智慧","zhì huì","wisdom"),
("冻","凍","dòng","freeze","冰冻","冰凍","bīng dòng","frozen"),
("餐","餐","cān","meal","早餐","早餐","zǎo cān","breakfast"),
("融","融","róng","melt","融化","融化","róng huà","melt"),
("剩","剩","shèng","remain","剩下","剩下","shèng xià","remain"),
("伐","伐","fá","cut down","砍伐","砍伐","kǎn fá","fell trees"),
("煤","煤","méi","coal","煤炭","煤炭","méi tàn","coal"),
("虑","慮","lǜ","consider","考虑","考慮","kǎo lǜ","consider"),
("献","獻","xiàn","offer","贡献","貢獻","gòng xiàn","contribute"),
("慎","慎","shèn","careful","谨慎","謹慎","jǐn shèn","cautious"),
("遗","遺","yí","leave behind","遗忘","遺忘","yí wàng","forget"),
("盗","盜","dào","steal","盗窃","盜竊","dào qiè","steal"),
("驾","駕","jià","drive","驾驶","駕駛","jià shǐ","drive"),
("质","質","zhì","quality","质量","質量","zhì liàng","quality"),
("议","議","yì","discuss","会议","會議","huì yì","meeting"),
("源","源","yuán","source","水源","水源","shuǐ yuán","water source"),
("享","享","xiǎng","enjoy","享受","享受","xiǎng shòu","enjoy"),
("叙","敘","xù","narrate","叙述","敘述","xù shù","narrate"),
("辽","遼","liáo","distant","辽阔","遼闊","liáo kuò","vast"),
("阔","闊","kuò","wide","辽阔","遼闊","liáo kuò","vast"),
("忧","憂","yōu","worry","忧愁","憂愁","yōu chóu","worry"),
("患","患","huàn","trouble","患者","患者","huàn zhě","patient"),
("搬","搬","bān","move","搬家","搬家","bān jiā","move house"),
("剧","劇","jù","drama","电视剧","電視劇","diàn shì jù","TV drama"),
("振","振","zhèn","shake","振动","振動","zhèn dòng","vibrate"),
("育","育","yù","educate","教育","教育","jiào yù","education"),
("良","良","liáng","good","良好","良好","liáng hǎo","good"),
("训","訓","xùn","train","训练","訓練","xùn liàn","train"),
("善","善","shàn","good","善良","善良","shàn liáng","kind"),
("谦","謙","qiān","modest","谦虚","謙虛","qiān xū","modest"),
("虚","虛","xū","empty","虚心","虛心","xū xīn","humble"),
]

GRADE5 = [
("窃","竊","qiè","steal","偷窃","偷竊","tōu qiè","steal"),
("锅","鍋","guō","pot","火锅","火鍋","huǒ guō","hot pot"),
("饿","餓","è","hungry","饥饿","飢餓","jī è","hungry"),
("惧","懼","jù","fear","恐惧","恐懼","kǒng jù","fear"),
("充","充","chōng","fill","充满","充滿","chōng mǎn","full of"),
("酸","酸","suān","sour","酸甜","酸甜","suān tián","sweet and sour"),
("甜","甜","tián","sweet","甜蜜","甜蜜","tián mì","sweet"),
("吵","吵","chǎo","noisy","吵闹","吵鬧","chǎo nào","noisy"),
("仁","仁","rén","kind","仁慈","仁慈","rén cí","benevolent"),
("贪","貪","tān","greedy","贪心","貪心","tān xīn","greedy"),
("津","津","jīn","ferry","天津","天津","tiān jīn","Tianjin"),
("偷","偷","tōu","steal","小偷","小偷","xiǎo tōu","thief"),
("扑","撲","pū","pounce","扑倒","撲倒","pū dǎo","fall forward"),
("莲","蓮","lián","lotus","莲花","蓮花","lián huā","lotus flower"),
("赋","賦","fù","bestow","天赋","天賦","tiān fù","talent"),
("淘","淘","táo","wash","淘气","淘氣","táo qì","naughty"),
("岂","豈","qǐ","how can","岂不","豈不","qǐ bù","wouldn't it"),
("豪","豪","háo","heroic","豪华","豪華","háo huá","luxurious"),
("誉","譽","yù","fame","荣誉","榮譽","róng yù","honor"),
("杆","桿","gǎn","pole","旗杆","旗桿","qí gǎn","flagpole"),
("腿","腿","tuǐ","leg","大腿","大腿","dà tuǐ","thigh"),
("陷","陷","xiàn","trap","陷阱","陷阱","xiàn jǐng","trap"),
("膝","膝","xī","knee","膝盖","膝蓋","xī gài","knee"),
("镇","鎮","zhèn","town","城镇","城鎮","chéng zhèn","town"),
("宾","賓","bīn","guest","宾客","賓客","bīn kè","guest"),
("朴","樸","pǔ","simple","朴素","樸素","pǔ sù","simple"),
("敏","敏","mǐn","quick","敏感","敏感","mǐn gǎn","sensitive"),
("悟","悟","wù","realize","领悟","領悟","lǐng wù","realize"),
("犬","犬","quǎn","dog","警犬","警犬","jǐng quǎn","police dog"),
("阶","階","jiē","step","阶段","階段","jiē duàn","stage"),
("纠","糾","jiū","correct","纠正","糾正","jiū zhèng","correct"),
("衰","衰","shuāi","decline","衰老","衰老","shuāi lǎo","aging"),
("彻","徹","chè","thorough","彻底","徹底","chè dǐ","thorough"),
("鉴","鑒","jiàn","mirror","鉴赏","鑒賞","jiàn shǎng","appreciate"),
("脊","脊","jǐ","spine","脊背","脊背","jǐ bèi","back"),
("链","鏈","liàn","chain","项链","項鏈","xiàng liàn","necklace"),
("蹲","蹲","dūn","squat","蹲下","蹲下","dūn xià","squat down"),
("脉","脈","mài","pulse","山脉","山脈","shān mài","mountain range"),
("旷","曠","kuàng","vast","旷野","曠野","kuàng yě","wilderness"),
("踢","踢","tī","kick","踢球","踢球","tī qiú","kick ball"),
("魂","魂","hún","soul","灵魂","靈魂","líng hún","soul"),
("浓","濃","nóng","thick","浓密","濃密","nóng mì","dense"),
("燥","燥","zào","dry","干燥","乾燥","gān zào","dry"),
("峻","峻","jùn","steep","严峻","嚴峻","yán jùn","severe"),
("崖","崖","yá","cliff","悬崖","懸崖","xuán yá","cliff"),
("弥","彌","mí","fill","弥漫","彌漫","mí màn","pervade"),
("频","頻","pín","frequent","频繁","頻繁","pín fán","frequent"),
("疾","疾","jí","disease","疾病","疾病","jí bìng","disease"),
("浆","漿","jiāng","pulp","豆浆","豆漿","dòu jiāng","soy milk"),
("勉","勉","miǎn","encourage","勉强","勉強","miǎn qiǎng","reluctant"),
]

GRADE6 = [
("挪","挪","nuó","move","挪动","挪動","nuó dòng","move"),
("蒸","蒸","zhēng","steam","蒸汽","蒸汽","zhēng qì","steam"),
("秧","秧","yāng","seedling","秧苗","秧苗","yāng miáo","seedling"),
("番","番","fān","time (MW)","番茄","番茄","fān qié","tomato"),
("锻","鍛","duàn","forge","锻炼","鍛煉","duàn liàn","exercise"),
("雅","雅","yǎ","elegant","优雅","優雅","yōu yǎ","elegant"),
("勃","勃","bó","vigorous","蓬勃","蓬勃","péng bó","vigorous"),
("施","施","shī","implement","实施","實施","shí shī","implement"),
("拔","拔","bá","pull out","拔河","拔河","bá hé","tug of war"),
("瘦","瘦","shòu","thin","瘦弱","瘦弱","shòu ruò","thin and weak"),
("饥","飢","jī","hungry","饥饿","飢餓","jī è","hungry"),
("蕴","蘊","yùn","contain","蕴含","蘊含","yùn hán","contain"),
("蜡","蠟","là","wax","蜡烛","蠟燭","là zhú","candle"),
("烛","燭","zhú","candle","蜡烛","蠟燭","là zhú","candle"),
("幽","幽","yōu","secluded","幽默","幽默","yōu mò","humor"),
("愁","愁","chóu","worry","忧愁","憂愁","yōu chóu","worry"),
("窜","竄","cuàn","flee","逃窜","逃竄","táo cuàn","flee"),
("祭","祭","jì","sacrifice","祭祀","祭祀","jì sì","sacrifice"),
("效","效","xiào","effect","效果","效果","xiào guǒ","effect"),
("憾","憾","hàn","regret","遗憾","遺憾","yí hàn","regret"),
("潜","潛","qián","dive","潜水","潛水","qián shuǐ","dive"),
("控","控","kòng","control","控制","控制","kòng zhì","control"),
("盲","盲","máng","blind","盲目","盲目","máng mù","blind"),
("哲","哲","zhé","wise","哲学","哲學","zhé xué","philosophy"),
("泣","泣","qì","weep","哭泣","哭泣","kū qì","weep"),
("锈","銹","xiù","rust","生锈","生銹","shēng xiù","rust"),
("填","填","tián","fill in","填写","填寫","tián xiě","fill in"),
("怨","怨","yuàn","resent","抱怨","抱怨","bào yuàn","complain"),
("掀","掀","xiān","lift","掀开","掀開","xiān kāi","lift open"),
("裹","裹","guǒ","wrap","包裹","包裹","bāo guǒ","package"),
("魁","魁","kuí","chief","魁梧","魁梧","kuí wú","stalwart"),
("淋","淋","lín","drench","淋雨","淋雨","lín yǔ","get rained on"),
("撑","撐","chēng","prop up","支撑","支撐","zhī chēng","support"),
("霉","霉","méi","mold","倒霉","倒霉","dǎo méi","unlucky"),
("删","刪","shān","delete","删除","刪除","shān chú","delete"),
("预","預","yù","advance","预习","預習","yù xí","preview"),
("耕","耕","gēng","plow","耕田","耕田","gēng tián","plow field"),
("辈","輩","bèi","generation","前辈","前輩","qián bèi","elder"),
("饶","饒","ráo","forgive","饶恕","饒恕","ráo shù","forgive"),
("恢","恢","huī","restore","恢复","恢復","huī fù","restore"),
("屈","屈","qū","bend","委屈","委屈","wěi qū","wronged"),
("障","障","zhàng","barrier","障碍","障礙","zhàng ài","obstacle"),
("覆","覆","fù","cover","覆盖","覆蓋","fù gài","cover"),
("壤","壤","rǎng","soil","土壤","土壤","tǔ rǎng","soil"),
("延","延","yán","extend","延长","延長","yán cháng","extend"),
("昔","昔","xī","past","昔日","昔日","xī rì","in the past"),
("莫","莫","mò","do not","莫名","莫名","mò míng","unexplained"),
("矛","矛","máo","spear","矛盾","矛盾","máo dùn","contradiction"),
("削","削","xuē","cut","削减","削減","xuē jiǎn","reduce"),
("贯","貫","guàn","pierce","贯穿","貫穿","guàn chuān","run through"),
("媒","媒","méi","media","媒体","媒體","méi tǐ","media"),
("抑","抑","yì","suppress","抑制","抑制","yì zhì","suppress"),
("挫","挫","cuò","setback","挫折","挫折","cuò zhé","setback"),
("卓","卓","zhuó","outstanding","卓越","卓越","zhuó yuè","outstanding"),
("兼","兼","jiān","together","兼职","兼職","jiān zhí","part-time"),
("慕","慕","mù","admire","羡慕","羨慕","xiàn mù","admire"),
("吟","吟","yín","chant","吟诵","吟誦","yín sòng","chant"),
]

def make_entry(char_data, grade, order):
    s, t, py, meaning, w, wt, wpy, wm = char_data
    return {
        "simplified": s,
        "traditional": t,
        "pinyin": py,
        "meaning": meaning,
        "gradeLevel": grade,
        "orderInGrade": order,
        "exampleWords": [{
            "word": w,
            "wordTraditional": wt,
            "pinyin": wpy,
            "meaning": wm,
            "ttsText": f"{s}，{w}的{s}"
        }]
    }

entries = []
for grade, data in [(1, GRADE1), (2, GRADE2), (3, GRADE3), (4, GRADE4), (5, GRADE5), (6, GRADE6)]:
    for i, char_data in enumerate(data):
        entries.append(make_entry(char_data, grade, i))

# Remove duplicates (keep first occurrence)
seen = set()
unique = []
for e in entries:
    if e["simplified"] not in seen:
        seen.add(e["simplified"])
        unique.append(e)

with open("/home/user/Chinese-Character-Writing/ChineseWriting/Resources/characters.json", "w", encoding="utf-8") as f:
    json.dump(unique, f, ensure_ascii=False, indent=2)

print(f"Generated {len(unique)} characters across grades 1-6")

# Count per grade
for g in range(1, 7):
    count = sum(1 for e in unique if e["gradeLevel"] == g)
    print(f"  Grade {g}: {count} characters")
